import { Alexandria} from "next/font/google";
import "./globals.css";

const alexandriaSans = Alexandria({
  variable: "--font-alexandria-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "Leo Frontend TEST",
  description: "Generated by Pietro Franchitti",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${alexandriaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
