import { Alexandria} from "next/font/google";
import "./globals.css";
import HeaderServer from "@/components/HeaderServer";

const alexandriaSans = Alexandria({
  variable: "--font-alexandria",
  subsets: ["latin"],
});



export const metadata = {
  title: "Leo Frontend TEST",
  description: "Generated by Pietro Franchitti",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${alexandriaSans.variable} antialiased`} lang="it">
      <body>
        <HeaderServer />
        {children}
      </body>
    </html>
  );
}
